### ISSUE TITLE
Can I authenticate SSH using password?

### ISSUE THREAD

**Issue by rodorgas** [Burnett01/rsync-deployments#28]
Is it possible to use password on SSH auth instead of a certificate? My provider doesn't allow publickey auth because home directories are only mounted on login.

**Comment by Burnett01** [comment]
Hello @rodorgas technically this is possible but not supported by this action mainly because scripted logins should be performed with keys. Passwords are sensitive information and shouldn't be used irresponsibly. While the password could be stored as a secret (similar to how the action allows it for passphrase-protected keys) it is still better to use keys over passwords.

**Comment by Burnett01** [comment]
Do you have a workaround on your system for using ssh keys? If not, I might add support for password login in a new version, though keys are the proper way of using the action.

**Comment by rodorgas** [comment]
@Burnett01 thank you for the quick reply! It's impossible to use ssh keys with this provider, but I managed to deploy using [this step](https://github.com/rodorgas/tcc/blob/020a72198b161c739360ed6f2da55f9faeb6eb2a/.github/workflows/gh-pages.yml#L45) (raw `sshpass` + `rsync` combo).

I understand this is an edge case so that's fine if you think it doesn't make sense to implement it right now. Maybe it will even encourage people to use password auth when they can use a certificate.
