### ISSUE TITLE
rsync deployment resulting in fail because received data is less than sent data

### ISSUE THREAD

**Issue by ankitmishra88** [Burnett01/rsync-deployments#38]
![image](https://user-images.githubusercontent.com/42653549/199985342-8383a398-5cbd-46dd-9755-d4856a66b038.png)
My github action workflow is resulting in failure, it says some files were not transferred, but all seems transferred.

**Comment by Burnett01** [comment]
this most likely refers to file attributes such as flags. I can't say what's causing this on your end, since I haven't experienced this problem. Which os are you using on your remote machine? What OS is the GH runner using? 
Please try to enable debug mode to rsync to see which files are involved: -v or -vv

**Comment by ankitmishra88** [comment]
Thanks for your @Burnett01 but it turned out that It was instance permission setting
